### PR TITLE
feat: Slim down anycall proxy

### PR DESCRIPTION
**Pull request by skellet0r**

### CODE REVIEW

**Review by michwill — APPROVED** [review]

**Comment by gaozhengxin** [comment]
A few things to check
- Line 162: check return value
- Add this restriction in AnyCall: `require(toChainID != block.chainid, "AnyCall: FORBID");`
- Line 220: reset pending address to 0 `pending = address(0);`

**Comment by skellet0r** [comment]
> Add this restriction in AnyCall: require(toChainID != block.chainid, "AnyCall: FORBID");

Don't actually need this check since an address can only call address it's been whitelisted for. So instead I added that check to the `setWhitelist` function. It reduces the cost for the end user and prevents the MPC from allowing that behavior

**Comment by gaozhengxin** [comment]
Another idea to discuss.
In most cases, the from address is contract address, so the caller contract must have a method to call withdraw.
Also, in the case of more than 3 chains, if the caller contracts have different addresses, the ops will need to charge multiple callers on each chain.
So I would like to add this
```
mapping(address => address) funders; // key is caller address, value is its funder

modifier charge(address _from) {
    ...
    executionBudget[funders[_from]] -= totalCost;
}

function deposit(address _funder) external payable;
```

**Comment by skellet0r** [comment]
> In most cases, the from address is contract address, so the caller contract must have a method to call withdraw.

Yeah that's very true, in fact, in practically all cases the caller of `anyCall` will be a contract. So when integrators develop their contracts, they'll need to add methods to enable withdrawl in their contracts. Adding anything else will just increase complexity and gas/maintenance overhead.

> Also, in the case of more than 3 chains, if the caller contracts have different addresses, the ops will need to charge multiple callers on each chain.

This I need further clarification on? Adding in the extra mapping means an additional SLOAD + JUMPI (i.e. extra execution overhead). This seems like something left in the hands of integrators, i'e they can add methods into their functions to make deposits when they're called, the benefit is it's opt-in for the integrator.

Example:

```js
interface AnyCall {
    function anyCall(address _to, bytes calldata _data, address _fallback, uint _toChainID) external;
    function deposit(address _account) external payable;
    function executionBudget(address _addr) external returns(uint);
}

/// @title Source contract deployed on Ethereum
/// @dev Needs to be whitelisted in the AnyCallProxy contract
contract Foo {
    address public constant ANYCALL = address(0xdeadbeef);

    /// @notice Make an empty call to the contract deployed at this same address on FTM
    function makeCall() external {
        AnyCall(ANYCALL).anyCall(address(this), bytes4(keecak256("foo()")),address(0), 250);
    }
}


contract Bar {
    address public constant ANYCALL = address(0xdeadbeef);
    uint256 public count;

    /// @notice This function will be called by the integrator from the source chain
    function foo() external {
        require(msg.sender == ANYCALL);

        // increase the count in storage
        count++;
        
        // if we don't have any execution budget, deposit more FTM
        if (AnyCall(ANYCALL).executionBudget(address(this)) == 0) {
            AnyCall(ANYCALL).deposit{value: 10**18}(address(this));
        }
    }

}
```

**Comment by skellet0r** [comment]
Another idea, is allowing integrators to specify a callvalue for their cross chain call. The callvalue would be deducted from the execution budget of the caller.

```js
    function anyExec(
        address _from,
        address _to,
        bytes calldata _data,
        uint256 _callvalue,  // new
        address _fallback,
        uint256 _fromChainID
    ) external charge(_from) onlyMPC {
        context = Context({sender: _from, fromChainID: _fromChainID});
        if (_callvalue != 0) {  // new, or even cooler you can make this flashloan like and just check that balanceBefore == balanceAfter
              executionBudget[_from] -= _callvalue
         }
        (bool success, bytes memory result) = _to.call{value: _callvalue}(_data);  // updated
        context = Context({sender: address(0), fromChainID: 0});

        emit AnyExec(_from, _to, _data, success, result, _fallback, _fromChainID);
```

Again a call to `anyExec` will only fail if the `executionBudget` of `_from` is insufficient.


This is just a nice to have though, since the same effect can be achieved by the integrator creating a minimal wrapper target on the destination chain

**Comment by gaozhengxin** [comment]
Please check the log names. `LogAnyCall` or ``AnyCall` ?

**Comment by skellet0r** [comment]
thxs, fixed

**Comment by gaozhengxin** [comment]
> Another idea, is allowing integrators to specify a callvalue for their cross chain call. The callvalue would be deducted from the execution budget of the caller.
> 
> ```js
>     function anyExec(
>         address _from,
>         address _to,
>         bytes calldata _data,
>         uint256 _callvalue,  // new
>         address _fallback,
>         uint256 _fromChainID
>     ) external charge(_from) onlyMPC {
>         context = Context({sender: _from, fromChainID: _fromChainID});
>         if (_callvalue != 0) {  // new, or even cooler you can make this flashloan like and just check that balanceBefore == balanceAfter
>               executionBudget[_from] -= _callvalue
>          }
>         (bool success, bytes memory result) = _to.call{value: _callvalue}(_data);  // updated
>         context = Context({sender: address(0), fromChainID: 0});
> 
>         emit AnyExec(_from, _to, _data, success, result, _fallback, _fromChainID);
> ```
> 
> Again a call to `anyExec` will only fail if the `executionBudget` of `_from` is insufficient.
> 
> This is just a nice to have though, since the same effect can be achieved by the integrator creating a minimal wrapper target on the destination chain

Why will integrators need to reduce their budget?

**Comment by skellet0r** [comment]
> Why will integrators need to reduce their budget?

lol no idea, but could open up opportunities we don't yet know of. One idea is cross chain arbitrage .... but regardless it isn't necessary at all

**Pull request merged**
